name: Renovate
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write
  pull-requests: write
  issues: write
  repository-projects: write
  
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: renovate.json
          token: ${{ github.token }}
